title: Replit Theming
description: Resources for designing your own Replit theme
github_username: BD103
baseurl: "Replit-Theming"

# Build settings
theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      nav: true
